# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  variable1: value1
  variable2: value2
  variable3: $variable1-$variable2
  org: joshjohanning-org
  repo: action-variable-tests
  combined: $org/$repo

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: |
          echo ${{ env.variable1 }}
          echo $variable2
          echo ${{ env.variable3 }}
          
      - run: | 
         echo "variable1=newvalue" >> $GITHUB_ENV
         
      - run: |
          echo ${{ env.variable1 }}
          echo $variable2
          echo ${{ env.variable3 }}
          
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
        
      - name: dump github env variables
        run: |
          echo "${{ github.env }}"
          cat ${{ github.env }}
          
      - run: |
          echo "combined=$org/$repo" >> $GITHUB_ENV
          # loop through the github env variables and re-set them all to >> $GITHUB_ENV
          echo 
          
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with: 
          # Repository name with owner. For example, actions/checkout
          repository: ${{ env.combined }}

